apiVersion: v2
name: cart-service
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: redis
  version: 11.2.1
  repository: https://charts.bitnami.com/bitnami
